"""create users

The initial schema. Hand-written rather than autogenerated, because a template
has to ship a project that already runs: `alembic upgrade head` on a fresh
clone must create the table, and autogenerate cannot run before there is a
database to compare against.

It mirrors `app/models/user.py` column for column — migrations own the schema,
so the model must never be the thing that creates it.

Revision ID: 0001
Revises:
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "users",
        # sa.Uuid maps to native UUID on Postgres and CHAR(32) elsewhere, which
        # is what lets the same migration run against every storage supported.
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # Unique *and* indexed, exactly as the model declares it: email is the
    # natural key the service matches on, so the lookup has to be indexed and
    # the database — not the service — is what guarantees there is only one.
    op.create_index("ix_users_email", "users", ["email"], unique=True)


def downgrade() -> None:
    op.drop_index("ix_users_email", table_name="users")
    op.drop_table("users")
