"""create products

Mirrors `app/models/product.py` column for column — migrations own the schema,
so the model must never be the thing that creates it. See 0001 for why the
initial migrations are hand-written rather than autogenerated.

Revision ID: 0002
Revises: 0001
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "products",
        # sa.Uuid maps to native UUID on Postgres and CHAR(32) elsewhere, which
        # is what lets the same migration run against every storage supported.
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sku", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        # Text, not String: a description is prose. See the model.
        sa.Column("description", sa.Text(), nullable=False),
        # BigInteger cents — never NUMERIC or a float. Integer money cannot
        # drift, and 64 bits leaves no room for a rounding question to be asked.
        sa.Column("price_cents", sa.BigInteger(), nullable=False),
        sa.Column("stock", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # Unique *and* indexed, exactly as the model declares it: SKU is the natural
    # key the service matches on, so the lookup has to be indexed and the
    # database — not the service — is what guarantees there is only one.
    op.create_index("ix_products_sku", "products", ["sku"], unique=True)


def downgrade() -> None:
    op.drop_index("ix_products_sku", table_name="products")
    op.drop_table("products")
